// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    [Migration("20231208174110_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7905),
                            Name = "Books",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7941)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7945),
                            Name = "Movies",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7947)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7950),
                            Name = "Music",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7951)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7953),
                            Name = "Games",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7955)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7956),
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7958)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7959),
                            Name = "Computers",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7961)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7962),
                            Name = "Home",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7964)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7965),
                            Name = "Garden",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7967)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7968),
                            Name = "Tools",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7970)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7972),
                            Name = "Grocery",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7973)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7975),
                            Name = "Health",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7976)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7978),
                            Name = "Beauty",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7979)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7981),
                            Name = "Toys",
                            UpdatedAt = new DateTime(2023, 12, 8, 12, 41, 10, 200, DateTimeKind.Local).AddTicks(7982)
                        });
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Post");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Backend.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.Property<int>("PostsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("PostsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("PostTag");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PostTag", b =>
                {
                    b.HasOne("Backend.Models.Post", null)
                        .WithMany()
                        .HasForeignKey("PostsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
