// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    [Migration("20231129235457_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5833),
                            Name = "Books",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5861)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5863),
                            Name = "Movies",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5864)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5865),
                            Name = "Music",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5866)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5868),
                            Name = "Games",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5869)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5870),
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5871)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5872),
                            Name = "Computers",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5873)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5874),
                            Name = "Home",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5875)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5876),
                            Name = "Garden",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5877)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5879),
                            Name = "Tools",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5879)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5902),
                            Name = "Grocery",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5904)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5905),
                            Name = "Health",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5907)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5908),
                            Name = "Beauty",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5909)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5910),
                            Name = "Toys",
                            UpdatedAt = new DateTime(2023, 11, 29, 18, 54, 56, 918, DateTimeKind.Local).AddTicks(5911)
                        });
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
